// Code generated by MockGen. DO NOT EDIT.
// Source: ./contracts.go

// Package secret_repo is a generated GoMock package.
package secret_repo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	internal "github.com/sstalschus/secrets-api/internal"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// CreateSecret mocks base method.
func (m *MockIRepository) CreateSecret(ctx context.Context, secret *internal.Secret, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", ctx, secret, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockIRepositoryMockRecorder) CreateSecret(ctx, secret, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockIRepository)(nil).CreateSecret), ctx, secret, userID)
}

// FindAllByUserId mocks base method.
func (m *MockIRepository) FindAllByUserId(ctx context.Context, userID string) []internal.Secret {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserId", ctx, userID)
	ret0, _ := ret[0].([]internal.Secret)
	return ret0
}

// FindAllByUserId indicates an expected call of FindAllByUserId.
func (mr *MockIRepositoryMockRecorder) FindAllByUserId(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserId", reflect.TypeOf((*MockIRepository)(nil).FindAllByUserId), ctx, userID)
}

// FindSecretByID mocks base method.
func (m *MockIRepository) FindSecretByID(ctx context.Context, id string) (*internal.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSecretByID", ctx, id)
	ret0, _ := ret[0].(*internal.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSecretByID indicates an expected call of FindSecretByID.
func (mr *MockIRepositoryMockRecorder) FindSecretByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSecretByID", reflect.TypeOf((*MockIRepository)(nil).FindSecretByID), ctx, id)
}

// GenerateID mocks base method.
func (m *MockIRepository) GenerateID() primitive.ObjectID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateID")
	ret0, _ := ret[0].(primitive.ObjectID)
	return ret0
}

// GenerateID indicates an expected call of GenerateID.
func (mr *MockIRepositoryMockRecorder) GenerateID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateID", reflect.TypeOf((*MockIRepository)(nil).GenerateID))
}
